/**
 * Small angle calculator. Note that this is not exact, but is a fair
 * approximation for large distances and small angles.
 * 12-11-2012
 * v.01a
 * @author Ace_GCR_
 */
public class SmallAngleCalculator extends javax.swing.JFrame {
   public double angle_Value=0;
   public double distance_Value=0;
   public double actual_Size=0;
   public int dms_Setting=0;
    /**
     * Creates new form SmallAngleCalculator
     */
    public SmallAngleCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        DGSButtonGroup = new javax.swing.ButtonGroup();
        degree_Radio_Button = new javax.swing.JRadioButton();
        minutes_Radio_Button = new javax.swing.JRadioButton();
        seconds_Radio_Button = new javax.swing.JRadioButton();
        distance_Input_Field = new javax.swing.JTextField();
        actual_Input_Field = new javax.swing.JTextField();
        angular_Input_Field = new javax.swing.JTextField();
        distance_Label = new javax.swing.JLabel();
        actual_Size_Label = new javax.swing.JLabel();
        angular_Size_Label = new javax.swing.JLabel();
        calc_Distance_Button = new javax.swing.JButton();
        calc_Size_Buttton = new javax.swing.JButton();
        calc_Ang_Size_Button = new javax.swing.JButton();
        instructions_Panel = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Small Angle Calculator");
        setResizable(false);

        DGSButtonGroup.add(degree_Radio_Button);
        degree_Radio_Button.setSelected(true);
        degree_Radio_Button.setText("Degrees");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, DGSButtonGroup, org.jdesktop.beansbinding.ELProperty.create("${}"), degree_Radio_Button, org.jdesktop.beansbinding.BeanProperty.create("action"));
        bindingGroup.addBinding(binding);

        degree_Radio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree_Radio_ButtonActionPerformed(evt);
            }
        });

        DGSButtonGroup.add(minutes_Radio_Button);
        minutes_Radio_Button.setText("Minutes");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, DGSButtonGroup, org.jdesktop.beansbinding.ELProperty.create("${}"), minutes_Radio_Button, org.jdesktop.beansbinding.BeanProperty.create("action"), "");
        bindingGroup.addBinding(binding);

        minutes_Radio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutes_Radio_ButtonActionPerformed(evt);
            }
        });

        DGSButtonGroup.add(seconds_Radio_Button);
        seconds_Radio_Button.setText("Seconds");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, DGSButtonGroup, org.jdesktop.beansbinding.ObjectProperty.create(), seconds_Radio_Button, org.jdesktop.beansbinding.BeanProperty.create("action"));
        bindingGroup.addBinding(binding);

        seconds_Radio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seconds_Radio_ButtonActionPerformed(evt);
            }
        });

        distance_Input_Field.setText("0");
        distance_Input_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distance_Input_FieldActionPerformed(evt);
            }
        });

        actual_Input_Field.setText("0");
        actual_Input_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actual_Input_FieldActionPerformed(evt);
            }
        });

        angular_Input_Field.setText("0");
        angular_Input_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angular_Input_FieldActionPerformed(evt);
            }
        });

        distance_Label.setText("Distance");

        actual_Size_Label.setText("Actual Size");

        angular_Size_Label.setText("Angular Size");

        calc_Distance_Button.setText("Calculate Distance");
        calc_Distance_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_Distance_ButtonActionPerformed(evt);
            }
        });

        calc_Size_Buttton.setText("Calculate Actual Size");
        calc_Size_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_Size_ButttonActionPerformed(evt);
            }
        });

        calc_Ang_Size_Button.setText("Calculate Angular Size");
        calc_Ang_Size_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_Ang_Size_ButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Requires at least 2 values to be entered\nin order to be entered before attempting\nto calculate the 3rd.\nPress a calculate button to initiate. ");
        instructions_Panel.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructions_Panel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(angular_Size_Label)
                                    .addComponent(angular_Input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calc_Ang_Size_Button)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(distance_Label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degree_Radio_Button)
                            .addComponent(minutes_Radio_Button)
                            .addComponent(seconds_Radio_Button)
                            .addComponent(actual_Size_Label))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calc_Distance_Button)
                    .addComponent(distance_Input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actual_Input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calc_Size_Buttton))
                .addGap(94, 94, 94))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {actual_Input_Field, angular_Input_Field, distance_Input_Field});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(instructions_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seconds_Radio_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(degree_Radio_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minutes_Radio_Button)
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(angular_Size_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angular_Input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calc_Ang_Size_Button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actual_Size_Label)
                    .addComponent(distance_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actual_Input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distance_Input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calc_Size_Buttton)
                    .addComponent(calc_Distance_Button))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void angular_Input_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angular_Input_FieldActionPerformed
       angle_Value=Float.parseFloat(angular_Input_Field.getText());
       // convert to degrees if necessary.
       if (dms_Setting==1){
          angle_Value=angle_Value*60;
       } else if (dms_Setting==2){
          angle_Value=angle_Value+3600;
       }
    }//GEN-LAST:event_angular_Input_FieldActionPerformed

    private void distance_Input_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distance_Input_FieldActionPerformed
        distance_Value=Float.parseFloat(distance_Input_Field.getText());
    }//GEN-LAST:event_distance_Input_FieldActionPerformed

    private void degree_Radio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree_Radio_ButtonActionPerformed
        dms_Setting=0;     
    }//GEN-LAST:event_degree_Radio_ButtonActionPerformed

    private void minutes_Radio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutes_Radio_ButtonActionPerformed
        dms_Setting=1;  
    }//GEN-LAST:event_minutes_Radio_ButtonActionPerformed

    private void seconds_Radio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seconds_Radio_ButtonActionPerformed
        dms_Setting=2;  
    }//GEN-LAST:event_seconds_Radio_ButtonActionPerformed

    private void actual_Input_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actual_Input_FieldActionPerformed
               actual_Size=Float.parseFloat(actual_Input_Field.getText());      // TODO add your handling code here:
    }//GEN-LAST:event_actual_Input_FieldActionPerformed

    private void calc_Size_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_Size_ButttonActionPerformed
       // Actual Size = (Angular Size/57.3)*Distance
        double result;
        revert();
        result=(angle_Value/57.3)*distance_Value;
        String resultStr;
        resultStr = new String();
        resultStr=String.valueOf(result);
        actual_Input_Field.setText(resultStr);
    }//GEN-LAST:event_calc_Size_ButttonActionPerformed

    private void calc_Ang_Size_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_Ang_Size_ButtonActionPerformed
        // Angular Size=(Size/Distance)*57.3
        double result;
        String resultStr;
        resultStr = new String();
        revert();
        if (distance_Value!=0){
            result=(actual_Size/distance_Value)*57.3;
            resultStr=String.valueOf(result);
        } else {
            resultStr="Infinite";
        }
        angular_Input_Field.setText(resultStr);
    }//GEN-LAST:event_calc_Ang_Size_ButtonActionPerformed

    private void calc_Distance_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_Distance_ButtonActionPerformed
        // Distance=Size*(57.3/Angle)
        double result;
        String resultStr;
        resultStr = new String();
        revert();
        if (angle_Value!=0){
            result=actual_Size*(57.3/angle_Value);
            resultStr=String.valueOf(result);
        } else {
            resultStr="Infinite";
        }
        distance_Input_Field.setText(resultStr);        
    }//GEN-LAST:event_calc_Distance_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmallAngleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmallAngleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmallAngleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmallAngleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmallAngleCalculator().setVisible(true);
            }
        });
 
    }
    
    // Reverts Text input Field back to last usable state. 
    // avoids the problems of trying to calculate with an input value of "Infinite"
    private void revert(){
       String tmpStr;
       tmpStr=new String();
       tmpStr=String.valueOf(angle_Value);
       angular_Input_Field.setText(tmpStr);
       tmpStr=String.valueOf(distance_Value);
       distance_Input_Field.setText(tmpStr);
       tmpStr=String.valueOf(actual_Size);
       actual_Input_Field.setText(tmpStr);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DGSButtonGroup;
    private javax.swing.JTextField actual_Input_Field;
    private javax.swing.JLabel actual_Size_Label;
    private javax.swing.JTextField angular_Input_Field;
    private javax.swing.JLabel angular_Size_Label;
    private javax.swing.JButton calc_Ang_Size_Button;
    private javax.swing.JButton calc_Distance_Button;
    private javax.swing.JButton calc_Size_Buttton;
    private javax.swing.JRadioButton degree_Radio_Button;
    private javax.swing.JTextField distance_Input_Field;
    private javax.swing.JLabel distance_Label;
    private javax.swing.JScrollPane instructions_Panel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton minutes_Radio_Button;
    private javax.swing.JRadioButton seconds_Radio_Button;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
